import { DEFAULT_BLOG_POSTS, PILOT_PROJECT_REVIEW, SECOND_PROJECT_REVIEW, SUKHUMVIT_AREA_ROUNDUP, ART4D_ARTICLES } from "./default-content";

export const blogPosts = [...DEFAULT_BLOG_POSTS, PILOT_PROJECT_REVIEW, SECOND_PROJECT_REVIEW, SUKHUMVIT_AREA_ROUNDUP, ...ART4D_ARTICLES];
