/** Client-safe sample CSV generator (kept separate from server import parsers). */
export function generateSampleCsv(): string {
  const headers = [
    "title",
    "titleEn",
    "description",
    "descriptionEn",
    "highlights",
    "listingType",
    "propertyType",
    "price",
    "bedrooms",
    "bathrooms",
    "areaSqm",
    "landSqWah",
    "floor",
    "district",
    "districtEn",
    "btsStation",
    "btsLine",
    "address",
    "latitude",
    "longitude",
    "npaBank",
    "npaReferenceUrl",
    "projectSlug",
    "furnishing",
    "features",
    "images",
  ];

  const sampleRow = [
    "คอนโด 2 ห้องนอน อโศก",
    "2BR Condo Asoke",
    "คอนโดสวย ใกล้ BTS อโศก พร้อมเฟอร์นิเจอร์ครบ",
    "Beautiful condo near BTS Asoke, fully furnished",
    "ใกล้ BTS 100 เมตร, ใกล้ Emporium",
    "rent",
    "condo",
    "35000",
    "2",
    "2",
    "65",
    "",
    "25",
    "วัฒนา",
    "Watthana",
    "อโศก",
    "สุขุมวิท",
    "สุขุมวิท 21 วัฒนา กรุงเทพ",
    "13.7367",
    "100.5608",
    "",
    "",
    "life-sathorn-silom",
    "furnished",
    "สระว่ายน้ำ,ฟิตเนส,ที่จอดรถ",
    "https://example.com/img1.jpg,https://example.com/img2.jpg",
  ];

  return `${headers.join(",")}\n${sampleRow.join(",")}\n${[
    "คอนโด NPA กสิกร สาทร",
    "KBank NPA Condo Sathorn",
    "ทรัพย์ NPA ธนาคารกสิกรไทย ใกล้ BTS สุรศักดิ์",
    "KBank foreclosed condo near BTS Surasak",
    "ขายด่วน ราคาพิเศษ",
    "sale",
    "npa",
    "4200000",
    "1",
    "1",
    "42",
    "",
    "18",
    "สาทร",
    "Sathorn",
    "สุรศักดิ์",
    "สีลม",
    "สาทร กรุงเทพฯ",
    "13.7194",
    "100.5212",
    "กสิกรไทย",
    "https://example.com/npa-listing",
    "",
    "https://example.com/npa1.jpg",
  ].join(",")}`;
}
